---
title: "12-Load-Data-ATG9-LC3"
output: html_notebook
---

CSV import - *Mac*
*change input file path*
```{r}
testdata=read.csv(file="~/Desktop/29Jun21_analysis/NSW3017_basal_counts_29Jun21.csv",header=TRUE)
testdata$BvsS<-"Basal"
testdata$BafA<-"BafAN"
testdata$Rep<-4
nobs=nrow(testdata)
for (i in 1:nobs) {
  if (testdata[i,1]=="") {
    testdata[i,1]<-fname

  } 
  else {
    fname=testdata[i,1]

  }
}

```


CSV import - *Windows*
*MUST HAVE FILES IN R PROJECT WD* 
*change input file path*
```{r}
temp=read.csv(file="./ATG9-LC3/datasets/NSW4056_prelim_15Jun23.csv",header=TRUE)
temp$BvsS<-"Basal"
temp$Rep<-1
nobs=nrow(temp)
for (i in 1:nobs) {
  if (temp[i,1]=="") {
    temp[i,1]<-fname

  } 
  else {
    fname=temp[i,1]

  }
}

```

Adding type designation
*if necessary update substring values based on filename in input document*
*check capitalization of values*
```{r}
temp$Type<-NA
ntemp<-nrow(temp)


for (c in 1:ntemp) {
  if (substr(temp[c,1],35,35)=="W") {
    temp$Type[c]<-"WT"
  }
  else if (substr(temp[c,1],35,35)=="C") {
    temp$Type[c]<-"Control"
  }
  else if (substr(temp[c,1],35,35)=="T") {
    temp$Type[c]<-"tepsin"
  }
  else {
    temp$Type[c]<-"AP4E1"
  }
  
}
temp$Type<-factor(temp$Type, levels=c("WT", "Control", "tepsin", "AP4E1"))
```

*ADD LOGIC CHECKS*


#Data calculation operations

Get Sum of cell counts per type
```{r}
temp$CellSum<-NA
ntemp<-nrow(temp)

for (t in c("WT", "Control", "tepsin", "AP4E1")) {
  for (bs in c("Basal", "Starved")) {
    for (r in c("1", "2","3", "4")) {
      
       temp$CellSum[which(temp$Type==t & temp$BvsS==bs & temp$Rep==r)]<-sum(temp$SegCellCount[which(temp$Type==t & temp$BvsS==bs & temp$Rep==r)],na.rm = TRUE)
   
    }
  }
  }
```

