---
title: "20-Graph-Data"
output: html_notebook
---

---
*Optional to subset data*
```{r}
subsetCA<-tidy2[tidy2$Type == "Control" | tidy2$Type == "AP4E1",]

```


boxplots- Windows save file pathing
*filepathing is written for Windows*
```{r}
temp$Type<-factor(temp$Type, levels=c("WT", "Control", "tepsin", "AP4E1"))
temp$BvsS<-factor(temp$BvsS, levels=c("Basal", "Starved"))

#library(ggplot2)
#install.packages("remotes")
#remotes::install_github("coolbutuseless/ggpattern")
#library(ggpattern)
#library(viridis)

plotme<-function(dat,yaxis,labelme,mytitle){
   ggplot(dat,aes(x=Type,y=yaxis,fill=Type, pattern=BvsS)) + 
      #geom_boxplot(width=.7,position = position_dodge(0.9),alpha=0.5, outlier.shape = 20, outlier.size = -1) +
    #geom_jitter(position = position_jitterdodge(1.4),alpha=.6, color = "grey") +
    facet_wrap(~BvsS)+
    geom_jitter(position = position_jitterdodge(1.4),alpha=0.8, color= "dark grey") +
    stat_boxplot(geom = "errorbar", width = 0.4) +
    geom_boxplot_pattern(
    aes(),width=0.7,position = position_dodge(0.9),outlier.shape=NA, alpha=0.5,
            pattern_spacing = 0.1,
            pattern_fill = "black",
            pattern_angle = 25,
            pattern_density = 0.1,) + 
    
        guides(pattern = guide_legend(override.aes = list(fill = "white")),
        fill = guide_legend(override.aes = list(pattern = "none")))+
     ylab(labelme)+
     ggtitle(mytitle)+
     theme_minimal()+
     #scale_y_continuous(name=labelme,limits = c(.20,0.7))+
     theme(plot.title=element_text(hjust=.5))+
        scale_fill_viridis(discrete=TRUE,end=.85) +
        scale_color_viridis(discrete=TRUE,end=.85)+
        scale_pattern_manual(values = c(Basal = "none", Starved = "stripe"))
  
}

#tiff(file="./graphs/percGolATG9A_NSW4022_11Feb22.tiff",width=2000,height=3000,res=600)
plotme(temp,temp$PercGolATG9, "percent ATG9A in TGN","")
#dev.off()

#tiff(file="./graphs/MOC_NSW4022_scl032-08_11Feb22.tiff",width=2000,height=3000,res=600)
plotme(temp,temp$MandersMOC, "Manders Overlap Coefficient","")
#dev.off()

#tiff(file="./graphs/M1_NSW4022_scl05-09_11Feb22.tiff",width=2000,height=3000,res=600)
plotme(temp,temp$MandersM1, "M1: ATG9 in TGN","")
#dev.off()

#tiff(file="./graphs/M2_NSW4022_scl05-1_11Feb22.tiff",width=2000,height=3000,res=600)
plotme(temp,temp$MandersM2, "M2: TGN in ATG9","")
#dev.off()

#tiff(file="./graphs/PCC-ATG9A_NSW4022_scl02-07_11Feb22.tiff",width=2000,height=3000,res=600)
plotme(temp,temp$PearsonCoeff, "Pearson's correlation coefficient","ATG9A co-localization with TGN")
#dev.off()

#tiff(file="./graphs/nonGolATG9Vol_NSW4022_11Feb22.tiff",width=2000,height=3000,res=600)
plotme(temp,temp$nonGolATG9Vol, "object volume","non-Golgi ATG9A volume")
#dev.off()

#tiff(file="./graphs/nonGolATG9MaxInt_NSW4022_11Feb22.tiff",width=2000,height=3000,res=600)
plotme(temp,temp$nonGolATG9MaxInt, "fluorescence intensity","non-Golgi ATG9A Max Intensity")
#dev.off()

```

