---
title: "21-Graph-Rescue-Data"
output: html_notebook
---

<<<<<<< HEAD
*Optional to subset data*
```{r}
subsetCT<-tidy[tidy$Type == "Control" | tidy$Type == "tepsin",]



```


boxplots- Windows save file pathing
*filepathing is written for Windows*
#rename graphing file to temp based on which subset of data is desired
```{r}
temp$Type<-factor(temp$Type, levels=c("WT", "Control", "tepsin", "AP4E1"))
temp$BvsS<-factor(temp$Rescue, levels=c("unt", "WTtep", "LIRless", "Cterm"))

#library(ggplot2)
#install.packages("remotes")
#remotes::install_github("coolbutuseless/ggpattern")
#library(ggpattern)
#library(viridis)

plotme<-function(dat,yaxis,labelme,mytitle){
   ggplot(dat,aes(x=Type,y=yaxis,fill=Type, pattern=Rescue)) + 
      #geom_boxplot(width=.7,position = position_dodge(0.9),alpha=0.5, outlier.shape = 20, outlier.size = -1) +
    #geom_jitter(position = position_jitterdodge(1.4),alpha=.6, color = "grey") +
    facet_wrap(~Rescue)+
    geom_jitter(position = position_jitterdodge(1.4),alpha=0.8, color= "dark grey") +
    stat_boxplot(geom = "errorbar", width = 0.4) +
    geom_boxplot_pattern(
    aes(),width=0.7,position = position_dodge(0.9),outlier.shape=NA, alpha=0.5,
            pattern_spacing = 0.1,
            pattern_fill = "black",
            pattern_angle = 25,
            pattern_density = 0.1,) + 
    
        guides(pattern = guide_legend(override.aes = list(fill = "white")),
        fill = guide_legend(override.aes = list(pattern = "none")))+
     ylab(labelme)+
     ggtitle(mytitle)+
     theme_minimal()+
    scale_y_continuous(name=labelme,limits = c(0,20))+
     theme(plot.title=element_text(hjust=.5))+
        scale_fill_viridis(discrete=TRUE, end=.85) +
        scale_color_viridis(discrete=TRUE,end=.85)+
        scale_pattern_manual(values = c(unt = "none", WTtep = "stripe", LIRless = "circle", Cterm = "weave"))
  
}

#tiff(file="./rescue-analysis_22May22/graphs/percGolATG9A_NSW4039A_2Jun22.tiff",width=3000,height=8000,res=600)
#plotme(temp,temp$PercGolATG9, "percent ATG9A in TGN","")
#dev.off()

#tiff(file="./rescue-analysis_22May22/graphs/MOC_NSW4046-4048-4049_adjY-CT_noFW_21Sep22.tiff",width=3000,height=5000,res=600)
#plotme(temp,temp$MandersMOC, "Manders Overlap Coefficient","")
#dev.off()

#tiff(file="./rescue-analysis_22May22/graphs/M1_NSW4046-4048-4049_adjY-CT_noFW_21Sep22.tiff",width=3000,height=5000,res=600)
#plotme(temp,temp$MandersM1, "M1: ATG9 in TGN","")
#dev.off()

#tiff(file="./rescue-analysis_22May22/graphs/M2_NSW4046-4048-4049_adjY_21Sep22.tiff",width=3000,height=5000,res=600)
#plotme(temp,temp$MandersM2, "M2: TGN in ATG9","")
#dev.off()

#tiff(file="./rescue-analysis_22May22/graphs/PCC-ATG9A_NSW4039-4040-4041_14Jul22.tiff",width=3000,height=5000,res=600)
#plotme(temp,temp$PearsonCoeff, "Pearson's correlation coefficient","ATG9A co-localization with TGN")
#dev.off()

#tiff(file="./rescue-analysis_22May22/graphs/nonGolATG9Vol_0-20_NSW4046-4048-4049_21Sep22.tiff",width=3000,height=5000,res=600)
#plotme(temp,temp$nonGolATG9Vol, "object volume","non-Golgi ATG9A volume")
#dev.off()

#tiff(file="./graphs/cleaned-CTA/nonGolATG9MaxInt_CTA_NSW4019-4020-4022-4026_3Mar22.tiff",width=2000,height=3000,res=600)
#plotme(temp,temp$nonGolATG9MaxInt, "fluorescence intensity","non-Golgi ATG9A Max Intensity")
#dev.off()

#tiff(file="./graphs/cleaned-CTA/GolATG9MaxInt_CTA_NSW4019-4020-4022-4026_3Mar22.tiff",width=2000,height=3000,res=600)
#plotme(temp,temp$GolATG9MaxInt, "fluorescence intensity","Golgi ATG9A Max Intensity")
#dev.off()

#tiff(file="./graphs/cleaned-CTA/nonGolATG9Vol-perCell_CTA_NSW4019-4020-4022-4026_3Mar22.tiff",width=1800,height=2500,res=600)
#plotme(tidy,tidy$AveATG9VolPerCell, "average object volume/cell","Average non-Golgi ATG9A volume/cell")
#dev.off()

#tiff(file="./graphs/cleaned-CTA/nonGolATG9MaxInt-perCell_CTA_NSW4019-4020-4022-4026_3Mar22.tiff",width=2000,height=3000,res=600)
#plotme(tidy,tidy$AveATG9MaxIntPerCell, "fluorescence intensity","Average non-Golgi ATG9A Max Intensity/cell")
#dev.off()

#tiff(file="./graphs/cleaned-CTA/GolATG9MaxInt-perCell_CTA_NSW4019-4020-4022-4026_3Mar22.tiff",width=2000,height=3000,res=600)
#plotme(tidy,tidy$AveATG9gMaxIntPerCell, "fluorescence intensity","Average Golgi ATG9A Max Intensity/cell")
#dev.off()

```

violin plots- Windows save file pathing
*filepathing is written for Windows*
```{r}
temp$Type<-factor(temp$Type, levels=c("WT", "Control", "tepsin"))


library(ggplot2)
#install.packages("remotes")
#remotes::install_github("coolbutuseless/ggpattern")
#library(ggpattern)
#library(viridis)

plotme<-function(dat,yaxis,labelme,mytitle){
  
    ggplot(dat,aes(x=Type,y=yaxis,fill=Type)) +
    geom_violin(scale="count", width= 1.05, color="#424949", alpha=0.5) +
    geom_boxplot(width=0.2, color="#424949", outlier.shape=NA, alpha=0.2) +
    facet_wrap(~Rescue)+
    scale_y_continuous(limits =c(0,4000))+
     ylab(labelme)+
    ggtitle(mytitle)+
    theme_minimal()+
    #theme(plot.title=element_text(hjust=.5))
      scale_fill_viridis(discrete=TRUE,end=.85)
        #scale_color_viridis(discrete=TRUE,end=.85)+
        
}

#tiff(file="./rescue-analysis_22May22/graphs/nonGolATG9MaxInt_violin-box_NSW4048_15Sep22.tiff",width=10000,height=8000,res=600)
#plotme(temp, temp$nonGolATG9MaxInt, "fluorescence intensity (a.u.)","non-Golgi ATG9A Max Intensity")
#dev.off()

#tiff(file="./rescue-analysis_22May22/graphs/GolATG9MaxInt_violin-box_NSW4046-4048_15Sep22.tiff",width=10000,height=8000,res=600)
#plotme(temp, temp$GolATG9MaxInt, "fluorescence intensity (a.u.)","Golgi ATG9A Max Intensity")
#dev.off()

#tiff(file="./rescue-analysis_22May22/graphs/nonGolATG9MaxInt_violin-box_NSW4039A_2Jun22.tiff",width=8000,height=10000,res=600)
#plotme(temp, temp$nonGolATG9Vol, "fluorescence intensity (a.u.)","non-Golgi ATG9A volume")
#dev.off()

```

